POST http://localhost:8082/login
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="username"

john
--WebAppBoundary--
Content-Disposition: form-data; name="password"

123
--WebAppBoundary--
###


GET http://localhost:8082//foos/666
Accept: application/json

###

